# Generated by Django 4.2.7 on 2025-10-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文本消息'), ('image', '图片消息'), ('system', '系统消息')], default='text', max_length=10, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/', verbose_name='图片')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_deleted_by_sender', models.BooleanField(default=False, verbose_name='发送者删除')),
                ('is_deleted_by_receiver', models.BooleanField(default=False, verbose_name='接收者删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '私信消息',
                'verbose_name_plural': '私信消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count_user1', models.PositiveIntegerField(default=0, verbose_name='用户1未读消息数')),
                ('unread_count_user2', models.PositiveIntegerField(default=0, verbose_name='用户2未读消息数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '消息会话',
                'verbose_name_plural': '消息会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reply', '回复我的'), ('mention', '@我的'), ('like', '点赞我的'), ('follow', '关注我的'), ('system', '系统通知'), ('tieba', '贴吧通知')], max_length=10, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='推送通知')),
                ('notify_on_reply', models.BooleanField(default=True, verbose_name='回复通知')),
                ('notify_on_mention', models.BooleanField(default=True, verbose_name='@我通知')),
                ('notify_on_like', models.BooleanField(default=True, verbose_name='点赞通知')),
                ('notify_on_follow', models.BooleanField(default=True, verbose_name='关注通知')),
                ('notify_on_system', models.BooleanField(default=True, verbose_name='系统通知')),
                ('notify_on_tieba', models.BooleanField(default=True, verbose_name='贴吧通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知设置',
                'verbose_name_plural': '通知设置',
            },
        ),
    ]
