# Generated by Django 4.2.7 on 2025-10-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='贴吧名称')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='贴吧描述')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='tieba_avatars/', verbose_name='贴吧头像')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tieba_banners/', verbose_name='贴吧横幅')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='成员数')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='帖子数')),
                ('today_posts_count', models.PositiveIntegerField(default=0, verbose_name='今日帖子数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('join_need_approve', models.BooleanField(default=False, verbose_name='加入需要审核')),
                ('post_need_approve', models.BooleanField(default=False, verbose_name='发帖需要审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贴吧',
                'verbose_name_plural': '贴吧',
                'ordering': ['-members_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TiebaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='分类图标')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '贴吧分类',
                'verbose_name_plural': '贴吧分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TiebaFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
            ],
            options={
                'verbose_name': '贴吧关注',
                'verbose_name_plural': '贴吧关注',
            },
        ),
        migrations.CreateModel(
            name='TiebaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', '普通成员'), ('admin', '管理员'), ('owner', '吧主')], default='member', max_length=10, verbose_name='角色')),
                ('nickname_in_tieba', models.CharField(blank=True, max_length=50, verbose_name='贴吧内昵称')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='等级')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tiebas.tieba', verbose_name='贴吧')),
            ],
            options={
                'verbose_name': '贴吧成员',
                'verbose_name_plural': '贴吧成员',
            },
        ),
    ]
