# Generated by Django 4.2.7 on 2025-10-29 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiebas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiebamember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieba_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='tiebafollow',
            name='tieba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tiebas.tieba', verbose_name='贴吧'),
        ),
        migrations.AddField(
            model_name='tiebafollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieba_follows', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiebas', to='tiebas.tiebacategory', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterUniqueTogether(
            name='tiebamember',
            unique_together={('tieba', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tiebafollow',
            unique_together={('user', 'tieba')},
        ),
    ]
